name: pr-e2e-tests
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: setup-libvirt
      id: setup
      run: |
        sudo apt-get update
        sudo apt-get install qemu-kvm libvirt-bin

    - name: Install CF CLI
      id: install-cfcli
      run: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
        chmod +x cf
        env
        sudo mv cf /usr/local/bin
        cf version

    - name: Install CF dev
      id: install-cfdev
      run: |
        cf version
        cf install-plugin -f -r CF-Community cfdev > /dev/null
        cf dev telemetry --off
        cf dev start


