name: pr-e2e-tests
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: setup-libvirt
      id: setup
      run: |
        sudo apt install qemu-kvm libvirt-bin libvirt-doc 

    - name: Install CF CLI
      id: install-cfcli
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf-cli
        cf version

    - name: Install CF dev
      id: install-cfdev
      run: |
        cf install-plugin -r CF-Community cfdev
        cf dev start


